return {
  {
    "folke/which-key.nvim",
    event = "VimEnter",
    version = "3.17.0",
    opts = {
      delay = 0,
      icons = {
        mappings = vim.g.have_nerd_font,
        keys = vim.g.have_nerd_font and {} or {
          Up = "<Up> ",
          Down = "<Down> ",
          Left = "<Left> ",
          Right = "<Right> ",
          C = "<C-…> ",
          M = "<M-…> ",
          D = "<D-…> ",
          S = "<S-…> ",
          CR = "<CR> ",
          Esc = "<Esc> ",
          ScrollWheelDown = "<ScrollWheelDown> ",
          ScrollWheelUp = "<ScrollWheelUp> ",
          NL = "<NL> ",
          BS = "<BS> ",
          Space = "<Space> ",
          Tab = "<Tab> ",
          F1 = "<F1>",
          F2 = "<F2>",
          F3 = "<F3>",
          F4 = "<F4>",
          F5 = "<F5>",
          F6 = "<F6>",
          F7 = "<F7>",
          F8 = "<F8>",
          F9 = "<F9>",
          F10 = "<F10>",
          F11 = "<F11>",
          F12 = "<F12>",
        },
      },
      spec = {
        { "<leader>c", group = "[C]ode", mode = { "n", "x" } },
        { "<leader>r", group = "[R]ename" },
        { "<leader>s", group = "[S]earch" },
        { "<leader>sr", group = "[R]eplace" },
        { "<leader>w", group = "[W]orkspace" },
        { "<leader>t", group = "[T]rouble diagnostics" },
        { "<leader>T", group = "[T]odo List" },
        { "<leader>F", group = "[F]ix List" },
        { "<leader>g", group = "[G]it/[G]o" },
        { "<leader>gh", group = "[H]unk operations" },
        { "<leader>gb", group = "[B]lame operations" },
        { "<leader>d", group = "[D]ocument" },
        { "<leader>l", group = "[L]SP" },
        { "<leader>S", group = "[S]essions" },
      },
    },
  },
}
