-- Icon definitions for use across the configuration
local M = {}

M.diagnostics = {
  Error = " ",
  Warn = " ",
  Hint = " ",
  Info = " ",
}

M.git = {
  added = " ",
  modified = " ",
  removed = " ",
}

M.kinds = {
  Array = " ",
  Boolean = "󰨙 ",
  Class = " ",
  Codeium = "󰘦 ",
  Color = " ",
  Control = " ",
  Collapsed = " ",
  Constant = "󰏿 ",
  Constructor = " ",
  Copilot = " ",
  Enum = " ",
  EnumMember = " ",
  Event = " ",
  Field = " ",
  File = " ",
  Folder = " ",
  Function = "󰊕 ",
  Interface = " ",
  Key = " ",
  Keyword = " ",
  Method = "󰊕 ",
  Module = " ",
  Namespace = "󰦮 ",
  Null = " ",
  Number = "󰎠 ",
  Object = " ",
  Operator = " ",
  Package = " ",
  Property = " ",
  Reference = " ",
  Snippet = " ",
  String = " ",
  Struct = "󰆼 ",
  TabNine = "󰏚 ",
  Text = " ",
  TypeParameter = " ",
  Unit = " ",
  Value = " ",
  Variable = "󰀫 ",
}

M.ui = {
  ActiveLSP = "",
  ActiveTS = "",
  ArrowLeft = "",
  ArrowRight = "",
  Bookmarks = "",
  BufferClose = "󰅖",
  DapBreakpoint = "",
  DapBreakpointCondition = "",
  DapBreakpointRejected = "",
  DapLogPoint = ".>",
  DapStopped = "󰁕",
  Debugger = "",
  DefaultFile = "󰈙",
  Diagnostic = "󰒡",
  DiagnosticHint = "",
  DiagnosticInfo = "󰋼",
  Ellipsis = "…",
  Environment = "",
  FileTree = "󰙅",
  Fire = "",
  Folder = "󰉋",
  FolderEmpty = "󰜌",
  FolderOpen = "󰝰",
  Git = "󰊢",
  History = "󰄉",
  LineLeft = "▊",
  LineMiddle = "│",
  List = "",
  Lock = "󰍁",
  NewFile = "",
  Note = "󰍨",
  Package = "",
  Pencil = "󰏫",
  Plus = "",
  Project = "",
  Search = "󰍉",
  SignIn = "",
  SignOut = "",
  Tab = "󰌒",
  Table = "",
  Target = "󰀘",
  Telescope = "",
  Text = "󰉿",
  Tree = "",
  Triangle = "󰐊",
  TriangleShortArrowDown = "",
  TriangleShortArrowLeft = "",
  TriangleShortArrowRight = "",
  TriangleShortArrowUp = "",
}

return M
